### PR TITLE
About-component with Initial landing page layout

### PR DESCRIPTION
**Pull request by kampana**
1. Created /welcome routing for the landing page layout  - currently with the header and footer

image

2. Created About component 

3. WIP: Pending common components + Mobile responsive check

### CODE REVIEW

**Comment by kampana** [comment]
Hey @omerdn1 ,
I've implemented this About component and I was thinking - do we need to support localization at this point? maybe we should create a separated issue to support it all around?
Also, do we have a layout already for the landing page or should I create one? I have that `GlobalMargin` in the code I'd like to put in some common place where everyone could use.

**Comment by webforte** [comment]
Hi @kampana,
we discussed localization/internationalization earlier. The team thought, that it is too soon and would increase overhead for now and eventually slow us down.

For example, offering multiple languages would mean to do this for _every_ groups texts we're adding. So I think this should be postponed at the moment.

**Comment by webforte** [comment]
Sorry @kampana, I accidently published your draft PR, this seems to be irreversible atm.

Looking good, just a few quick questions: 

- You could create another route for the "new" landing page and insert the about page there? Right now this about component runs below the footer: https://deploy-preview-28--civictechhub.netlify.com/
- You can easily make user of the ready-to-use [<Container />](https://react.semantic-ui.com/elements/container/)-Components from `semantic-ui-react`. The [Grid](https://react.semantic-ui.com/collections/grid/) is a good starting point for layouting responsive Rows & Cols.

**Comment by kampana** [comment]
> Sorry @kampana, I accidently published your draft PR, this seems to be irreversible atm.
> 
> Looking good, just a few quick questions:
> 
> * You could create another route for the "new" landing page and insert the about page there? Right now this about component runs below the footer: https://deploy-preview-28--civictechhub.netlify.com/

The About component was added below the footer just for the testing purposes, thats why the PR was set to in progress :-)
Will work on that landing route!

> * You can easily make user of the ready-to-use -Components from `semantic-ui-react`. The [Grid](https://react.semantic-ui.com/collections/grid/) is a good starting point for layouting responsive Rows & Cols.

Will do that.
Just to make sure, nobody have done that already for now?

**Comment by kampana** [comment]
@webforte , I've updated the merge request with the comment and also noted that I've created a temporary /welcome routing to test the About component, as the currently layout still shows redundant header and footer. Should we do that on a separated task?

**Comment by omerdn1** [comment]
@kampana Very nice and clean! I'm thinking we should hold off until #41 is done because we might end up migrating from SemanticUI. Additionally, the about component underwent some changes and we should probably already adjust to fit the design:
Screen Shot 2020-03-30 at 13 04 44

**Comment by kampana** [comment]
> @kampana Very nice and clean! I'm thinking we should hold off until #41 is done because we might end up migrating from SemanticUI. Additionally, the about component underwent some changes and we should probably already adjust to fit the design:
> Screen Shot 2020-03-30 at 13 04 44
> 
> Here's a suggested text for the about component by a member of the content team:
> 
> > We are CivicTechHub, a bunch of diverse and driven global people. We want to save lives and hack to support our global society. This Corona crisis is requiring nearly all of us to stay at home, slow the spread of COVID-19 and to work remotely. We want to be levers of change managing to overcome this crisis the world is facing. In this trying and unprecedented time we have created a central hub that connects people in need & people with solutions.
> 
> > We are pleased to tell you that, even in lockdown, there is a central hub - CivicTechHub - a place for connection that  can make a world of difference to someone struggling through what will be a challenging and lonely period of lockdown.

What an awesome design!!! 
Where can I find the picture to embed this? 

I'll follow up on #41

**Comment by omerdn1** [comment]
Getting the image from Bavo/Hannelore for you

**Comment by kampana** [comment]
@omerdn1 , notice the updated comments. Implemented the new design, pending the common components and replacement of semantic-ui.

**Comment by kampana** [comment]
Replaced with https://github.com/civictechhub/client/pull/48

**Pull request closed without merging**
